version: '3.8'

services:

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: websmds-frontend
    restart: always
    env_file: "./frontend/.env"
    # environment:
    #   -
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - websmds-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: websmds-backend
    restart: always
    env_file: "./backend/.env"
    # environment:
    #   -
    ports:
      - "5001:5000"
    networks:
      - websmds-network

  
networks:
  websmds-network:
    driver: bridge